// Word bank — one "russian,english" pair per line.
// Add or edit lines freely; the parser below handles the rest.
const WORDS = (function () {
  const raw = `август,August
автобус,bus
адрес,address
аптека,pharmacy
армия,army
артист,artist-performer
атака,attack
атом,atom
аэропорт,airport
авария,accident-breakdown
агент,agent
адвокат,lawyer
академия,academy
аквариум,aquarium
актёр,actor
акция,action-share-promotion
аллея,alley-avenue
альбом,album
анализ,analysis
анкета,form-questionnaire
ансамбль,ensemble
апельсин,orange
аппарат,apparatus-device
аппетит,appetite
арбуз,watermelon
аргумент,argument
арест,arrest
аромат,aroma
архив,archive
астроном,astronomer
аудитория,audience-classroom
авторитет,authority
агрессия,aggression
активный,active
алый,scarlet
ангел,angel
архитектор,architect
аспект,aspect
атлас,atlas-satin
афиша,poster-playbill
абзац,paragraph
абонент,subscriber
авиация,aviation
автор,author
агентство,agency
азбука,alphabet-primer
айсберг,iceberg
акцент,accent
алмаз,diamond
аптекарь,pharmacist
бабушка,grandmother
багаж,luggage
база,base
баланс,balance
балкон,balcony
банк,bank
баня,bathhouse
бар,bar
бассейн,pool
башня,tower
бег,running
беда,trouble-misfortune
белка,squirrel
белый,white
берег,shore
берёза,birch
беседа,conversation
библиотека,library
бизнес,business
билет,ticket
бинокль,binoculars
биология,biology
благо,good-benefit
бланк,form-sheet
блеск,shine-glitter
блин,pancake
блок,block
бобр,beaver
богатый,rich
боец,fighter
бой,fight-battle
бок,side
болезнь,illness
болото,swamp
боль,pain
большой,big
борт,board-side
босс,boss
бот,bot
брат,brother
бревно,log
бригада,brigade-crew
бровь,eyebrow
бронза,bronze
брюки,trousers
буква,letter
букет,bouquet
бумага,paper
бусы,beads
бутылка,bottle
вагон,carriage
ванна,bath
варенье,jam
вариант,variant-option
вата,cotton
вдова,widow
ведро,bucket
век,century-age
великий,great
велосипед,bicycle
вена,vein
веник,broom
вера,faith
верблюд,camel
верёвка,rope
верный,faithful-correct
вес,weight
весело,cheerfully
весна,spring
весть,news-tidings
ветер,wind
ветка,branch
вечер,evening
вещь,thing
взгляд,glance-view
взнос,contribution
взрыв,explosion
вид,view-kind
виза,visa
вилка,fork
вино,wine
вирус,virus
вклад,contribution-deposit
вкус,taste
власть,power
влияние,influence
вниз,down
внимание,attention
внук,grandson
вода,water
вождь,leader
воз,cart
война,war
вокзал,station
волк,wolf
волна,wave
воля,will-freedom
вор,thief
ворота,gate
восток,east
гавань,harbor
газ,gas
газета,newspaper
галстук,tie
гараж,garage
гвоздь,nail
гений,genius
география,geography
герб,coat-of-arms
герой,hero
гибель,death-doom
гид,guide
гимн,anthem
гипотеза,hypothesis
глава,chapter-head
гладкий,smooth
глаз,eye
глина,clay
глубина,depth
глупый,stupid
гнездо,nest
год,year
гол,goal
голова,head
голос,voice
голубь,pigeon
гора,mountain
горе,grief
горло,throat
город,city
горох,peas
гости,guests
гость,guest
государство,state
готовый,ready
град,hail-city
граница,border
графика,graphics
гребень,comb-crest
грех,sin
гриб,mushroom
грипп,flu
гром,thunder
грудь,chest
груз,cargo
группа,group
грязь,mud
губа,lip
гудок,horn-buzzer
гусь,goose
давление,pressure
далёкий,distant
дама,lady
дань,tribute
дата,date
дача,cottage
дверь,door
движение,movement
двор,yard
дебют,debut
девочка,girl
дед,grandfather
дело,matter-business
день,day
деньги,money
депутат,deputy
деревня,village
дерево,tree
держава,power-state
десерт,dessert
дети,children
деталь,detail-part
дешёвый,cheap
деятель,figure-activist
диагноз,diagnosis
диалог,dialogue
диван,sofa
дивизия,division
диета,diet
дизайн,design
дикий,wild
диплом,diploma
директор,director
диск,disk
дитя,child
длина,length
дно,bottom
добро,good
добыча,extraction-prey
довод,argument-reason
договор,contract
дождь,rain
доклад,report
доктор,doctor
документ,document
долг,debt-duty
долина,valley
дом,house
доска,board
дочь,daughter
жаба,toad
жадный,greedy
жакет,jacket
жалоба,complaint
жалость,pity
жанр,genre
жара,heat
жареный,fried
жасмин,jasmine
жатва,harvest
жать,to-press-reap
жвачка,gum
жевать,to-chew
желание,wish-desire
желе,jelly
железо,iron
желток,yolk
жёлтый,yellow
желудок,stomach
жена,wife
жених,fiancé
жерло,muzzle-crater
жертва,victim
жестокий,cruel
жесть,tin-harshness
жест,gesture
живой,alive
живот,belly
жидкий,liquid
жизнь,life
жила,vein
жилет,vest
жилище,dwelling
жир,fat
житель,inhabitant
жребий,lot-fate
жрец,priest
жулик,swindler
журавль,crane
журнал,magazine
жук,beetle
жужжать,to-buzz
жуть,dread
жюри,jury
жёсткий,hard-rigid
жажда,thirst
жалеть,to-pity
ждать,to-wait
желанный,desired
жемчуг,pearl
забава,amusement
забор,fence
завод,factory
завтра,tomorrow
завтрак,breakfast
загадка,riddle
заговор,conspiracy
зад,rear
задание,task
задача,task-problem
зажим,clamp
зайка,bunny
заказ,order
закат,sunset
закон,law
залив,bay
залог,pledge
замок,lock-castle
запад,west
запас,stock
запись,record-note
запрос,request-query
зараза,infection
заряд,charge
заслон,barrier
засуха,drought
затвор,bolt
затея,venture
захват,capture
зачёт,credit-test
защита,defense
заяц,hare
звание,title-rank
звено,link
зверь,beast
звон,ringing
звук,sound
здание,building
здесь,here
здоровье,health
земля,earth-land
зеркало,mirror
зерно,grain
зима,winter
злоба,malice
змея,snake
знамя,banner
знание,knowledge
зонт,umbrella
зрение,vision
ива,willow
игла,needle
игра,game
идеал,ideal
идея,idea
идол,idol
идти,to-go
изба,hut
избыток,surplus
известие,news
известный,known
изгиб,bend
изделие,product
издание,edition
изюм,raisin
излишек,excess
изменение,change
измерение,measurement
износ,wear
изобилие,abundance
изумруд,emerald
икра,caviar
или,or
имя,name
индюк,turkey
инженер,engineer
инициатива,initiative
инструмент,tool-instrument
интервал,interval
интерес,interest
интернет,internet
ирис,iris
ирония,irony
иск,lawsuit
искусство,art
ислам,Islam
испуг,fright
исследование,research
истина,truth
история,history-story
итог,total
ишак,donkey
ищейка,bloodhound
июль,July
июнь,June
икона,icon
иллюзия,illusion
импорт,import
инстинкт,instinct
институт,institute
кабинет,office-study
каблук,heel
кавалер,gentleman
кадр,frame-shot
каждый,each
казак,Cossack
казнь,execution
кайма,edge
какао,cocoa
камень,stone
камин,fireplace
канал,channel
канат,rope-cable
кандидат,candidate
каникулы,holidays
канон,canon
капкан,trap
капля,drop
капот,hood
каприз,whim
капуста,cabbage
карман,pocket
карта,map-card
картина,picture
картон,cardboard
картофель,potato
касса,cashier-till
кастрюля,pot
катастрофа,catastrophe
катер,boat
каток,rink
кафедра,chair-department
кашель,cough
каюта,cabin
квадрат,square
квартира,apartment
квас,kvass
кедр,cedar
кекс,cupcake
кенгуру,kangaroo
кепка,cap
керамика,ceramics
керосин,kerosene
кино,cinema
кирпич,brick
кислый,sour
кислород,oxygen
кит,whale
клён,maple
книга,book
лаборатория,laboratory
лава,lava
лавка,bench-shop
лагерь,camp
ладонь,palm
ладья,rook-boat
лазер,laser
лай,barking
лак,varnish
лампа,lamp
ландыш,lily-of-the-valley
лапа,paw
ларёк,stall
ласка,caress-weasel
ласточка,swallow
лауреат,laureate
лебедь,swan
лев,lion
легенда,legend
лёгкий,light-easy
лёд,ice
лежать,to-lie
лекция,lecture
лента,ribbon-tape
лепесток,petal
лес,forest
лестница,staircase
лето,summer
лечить,to-treat
леший,wood-sprite
лжец,liar
лидер,leader
лилия,lily
лимон,lemon
линия,line
липа,linden
лиса,fox
лист,leaf-sheet
литература,literature
лить,to-pour
лифт,elevator
лихорадка,fever
лицо,face
личность,personality
лишний,extra
лоб,forehead
ловкий,dexterous
логика,logic
ложка,spoon
локоть,elbow
магазин,shop
магия,magic
магнит,magnet
мазь,ointment
май,May
майка,t-shirt
мак,poppy
макет,model-layout
малый,small
мальчик,boy
мама,mom
манго,mango
манера,manner
манжет,cuff
мания,mania
мантия,mantle
марка,stamp-brand
март,March
марш,march
маска,mask
масло,oil-butter
масса,mass
мастер,master
масштаб,scale
математика,mathematics
матч,match
мать,mother
машина,car-machine
маяк,lighthouse
мгла,haze
мебель,furniture
медаль,medal
медведь,bear
мёд,honey
медицина,medicine
мел,chalk
мель,shallows
мемуары,memoirs
меньше,less
меню,menu
мера,measure
метла,broom
метод,method
метр,meter
мечта,dream
мешок,sack
миг,instant
милиция,police
милый,dear-cute
минута,minute
набережная,embankment
наблюдение,observation
набор,set
навес,canopy
награда,reward
надежда,hope
надзор,supervision
назад,back
название,name-title
наивный,naive
наказ,mandate
наклон,slope
наконец,finally
налог,tax
намерение,intention
напасть,misfortune
напор,pressure
направление,direction
например,for-example
народ,people
насос,pump
наследие,heritage
наст,crust
настой,infusion
настрой,mood
наступление,advance
насчёт,regarding
натиск,onslaught
наука,science
нация,nation
начало,beginning
начальник,boss
небо,sky
невеста,bride
неделя,week
недуг,ailment
нельзя,forbidden
немец,German
ненависть,hatred
неон,neon
нерв,nerve
несчастье,misfortune
нет,no
нефть,oil
нива,field
низ,bottom
никель,nickel
нитка,thread
ниша,niche
новость,news
обед,lunch
обещание,promise
обида,offense
область,region
облако,cloud
оборона,defense
образ,image
обувь,footwear
обучение,training
объём,volume
обычай,custom
овраг,ravine
огонь,fire
огурец,cucumber
одежда,clothing
одеяло,blanket
ожог,burn
озеро,lake
окно,window
около,near
окоп,trench
олень,deer
олива,olive
омлет,omelet
он,he
опасность,danger
опера,opera
опора,support
орден,order-medal
орех,nut
орёл,eagle
оружие,weapon
оса,wasp
осень,autumn
осмотр,inspection
основа,basis
остров,island
отвага,courage
ответ,answer
отец,father
отряд,detachment
отпуск,leave-vacation
офис,office
охота,hunting-wish
очерк,essay
очки,glasses
ошибка,mistake
ожерелье,necklace
океан,ocean
оратор,orator
павильон,pavilion
павлин,peacock
паёк,ration
палата,chamber-ward
палец,finger
палитра,palette
палка,stick
палуба,deck
память,memory
панель,panel
паника,panic
пансионат,boarding-house
папа,dad
пар,steam
парад,parade
парик,wig
парк,park
пароль,password
пароход,steamship
парта,desk
парус,sail
пасха,Easter
патент,patent
пауза,pause
паук,spider
пафос,pathos
пах,groin
пацан,lad
пачка,pack
пашня,field
певец,singer
пейзаж,landscape
пекарь,baker
пенал,pencil-case
пение,singing
пепел,ash
перец,pepper
перо,feather-pen
песня,song
песок,sand
печать,seal-press
печень,liver
пещера,cave
пианино,piano
пиво,beer
пижама,pajamas
пилот,pilot
пирог,pie
письмо,letter
пища,food
работа,work
раб,slave
радар,radar
радио,radio
радость,joy
раз,time-once
разум,mind
рай,paradise
рак,cancer-crayfish
ракета,rocket
рама,frame
рана,wound
ранг,rank
рапорт,report
рассвет,dawn
рассказ,story
раствор,solution
рация,walkie-talkie
рвение,zeal
реакция,reaction
ребро,rib
ребёнок,child
рев,roar
революция,revolution
регион,region
редко,rarely
режим,regime-mode
резать,to-cut
рейс,flight-trip
река,river
реклама,advertisement
рекорд,record
рельс,rail
ремень,belt
ремонт,repair
репа,turnip
ресурс,resource
реферат,abstract-paper
реформа,reform
речь,speech
решение,decision
решётка,grating
рис,rice
риск,risk
ритм,rhythm
риф,reef
робот,robot
род,kind-clan
родина,homeland
роза,rose
сад,garden
салат,salad
салют,salute
сам,self
самолёт,airplane
сани,sled
сапог,boot
сарай,shed
сахар,sugar
свеча,candle
свет,light
свинец,lead
свобода,freedom
свод,vault
связь,connection
сгиб,bend
сдача,change-delivery
сеанс,session
север,north
седло,saddle
сезон,season
секрет,secret
сектор,sector
село,village
семья,family
сентябрь,September
сердце,heart
серия,series
серый,grey
сестра,sister
сеть,net
сжатие,compression
сигнал,signal
сила,strength
символ,symbol
синий,blue
сироп,syrup
система,system
ситец,calico
ситуация,situation
сиять,to-shine
скала,rock
скамья,bench
скарб,belongings
скелет,skeleton
скидка,discount
склад,warehouse
скорость,speed
скрипка,violin
слава,glory
табак,tobacco
таблетка,pill
табло,display-board
таз,basin
тайга,taiga
тайна,secret
так,so
такси,taxi
талант,talent
талия,waist
талисман,talisman
таможня,customs
танец,dance
танк,tank
тапки,slippers
тара,packaging
тарелка,plate
тариф,tariff
творог,cottage-cheese
творчество,creativity
театр,theater
тезис,thesis
текст,text
телевизор,TV
телефон,telephone
тело,body
тема,theme
темнота,darkness
тенор,tenor
тень,shadow
теория,theory
тепло,warmth
терапевт,physician
термин,term
террор,terror
тест,test
тетрадь,notebook
тигр,tiger
тираж,circulation
тишина,silence
ткань,fabric
товар,goods
ток,current
толпа,crowd
том,volume
тон,tone
топор,axe
торг,trade
точка,point-dot
трава,grass
убеждение,conviction
убор,attire
уборка,cleaning
убыток,loss
уважение,respect
уговор,agreement
угол,corner
уголь,coal
удача,luck
удар,blow
удочка,fishing-rod
ужин,dinner
узор,pattern
указ,decree
улица,street
улыбка,smile
ум,mind
умение,skill
униформа,uniform
университет,university
упадок,decline
упор,support
управление,management
упражнение,exercise
урожай,harvest
урок,lesson
уровень,level
усилие,effort
условие,condition
услуга,service
устав,charter
утро,morning
утюг,iron
уход,care-departure
участок,plot
учебник,textbook
ученик,pupil
учёба,studies
учёный,scholar
ущелье,gorge
уют,comfort
узник,prisoner
улитка,snail
улей,hive
уныние,despondency
упрёк,reproach
урна,urn
успех,success
утка,duck
ухо,ear
фабрика,factory
фазан,pheasant
факел,torch
факт,fact
факультет,faculty
фальшь,falseness
фамилия,surname
фан,fan
фантазия,fantasy
фара,headlight
фарфор,porcelain
фасад,facade
фасоль,beans
фашист,fascist
февраль,February
федерация,federation
фейерверк,fireworks
фельдшер,paramedic
фен,hairdryer
феномен,phenomenon
ферма,farm
фестиваль,festival
фигура,figure
физика,physics
фикус,ficus
филин,eagle-owl
фильм,film
финал,finale
финансы,finance
финик,date
фирма,firm
фитиль,wick
флаг,flag
флакон,vial
фланг,flank
флейта,flute
флот,fleet
фокус,trick-focus
фольга,foil
фон,background
фонтан,fountain
форма,form
форум,forum
фосфор,phosphorus
фото,photo
фраза,phrase
фрак,tailcoat
футбол,football
фуражка,cap
фрукт,fruit
халат,robe
халва,halva
характер,character
хвост,tail
хвоя,needles
хижина,hut
химия,chemistry
хирург,surgeon
хитрый,cunning
хлеб,bread
хлев,barn
хлопок,cotton
хобби,hobby
ход,move
хозяин,owner
холод,cold
холм,hill
хор,choir
хорёк,ferret
хотеть,to-want
храм,temple
храп,snoring
хребет,ridge
хрен,horseradish
хрип,wheeze
христианин,Christian
хроника,chronicle
хрусталь,crystal
хрюшка,piggy
худой,thin
хулиган,hooligan
хурма,persimmon
хозяйство,household
халтура,hack-work
хам,boor
хан,khan
хаос,chaos
хартия,charter
хвалить,to-praise
хватка,grip
хворать,to-ail
химера,chimera
хитрость,cunning
хлебороб,grain-grower
хлопоты,troubles
хмурый,gloomy
ходьба,walking
храбрый,brave
хрупкий,fragile
худеть,to-lose-weight
цапля,heron
царь,tsar
цвет,color
цветок,flower
цель,goal
цена,price
центр,center
цепь,chain
церковь,church
цирк,circus
цифра,digit
цоколь,base
цемент,cement
ценз,qualification
церемония,ceremony
циклон,cyclone
цилиндр,cylinder
цинк,zinc
цитата,quote
цитрус,citrus
цокот,clatter
цукат,candied-fruit
цунами,tsunami
цыган,gypsy
цыплёнок,chick
цедра,zest
целина,virgin-soil
целлофан,cellophane
целостность,integrity
цельность,wholeness
цементный,cement
центнер,centner
цепочка,chain
церковный,church
цивилизация,civilization
цикорий,chicory
цинизм,cynicism
циновка,mat
циркуль,compass
цистерна,tank
цитадель,citadel
цитология,cytology
цифровой,digital
цукини,zucchini
цыганка,gypsy
ценность,value
цент,cent
цех,workshop
цикл,cycle
цок,clink
чай,tea
чайник,kettle
час,hour
частица,particle
часть,part
часы,clock
чашка,cup
человек,person
чемодан,suitcase
чемпион,champion
череп,skull
черёмуха,bird-cherry
чернила,ink
чёрный,black
чертёж,drawing
чеснок,garlic
честь,honor
четверг,Thursday
четверть,quarter
число,number
чистый,clean
читатель,reader
чтение,reading
чтобы,in-order-that
чуб,forelock
чугун,cast-iron
чудеса,wonders
чужой,stranger
чулок,stocking
чучело,scarecrow
чушь,nonsense
чадо,offspring
чайка,seagull
чалма,turban
чан,vat
чарка,cup
чародей,sorcerer
чахотка,consumption
чаща,thicket
чванство,arrogance
чебурек,cheburek
чекан,chaser
чек,check
челнок,shuttle
чемпионат,championship
чепец,cap
червь,worm
через,through
черта,line
чехол,cover
шаг,step
шайба,puck
шалаш,hut
шаль,shawl
шампиньон,champignon
шанс,chance
шапка,hat
шар,ball
шарф,scarf
шахта,mine
шахматы,chess
шашлык,shashlik
швабра,mop
швед,Swede
швейцар,doorman
швея,seamstress
швы,seams
шедевр,masterpiece
шёлк,silk
шелест,rustle
шёпот,whisper
шерсть,wool
шест,pole
шеф,boss-chef
шея,neck
шило,awl
шина,tire
шинель,overcoat
шип,thorn
ширь,expanse
шкаф,cupboard
шкатулка,box
школа,school
шкура,skin-hide
шланг,hose
шлем,helmet
шлюпка,boat
шляпа,hat
шов,seam
шок,shock
шоколад,chocolate
шорты,shorts
шоссе,highway
шофёр,driver
шпага,sword
шприц,syringe
штаб,staff
штора,curtain
штука,thing-piece
шум,noise
яблоко,apple
яблоня,apple-tree
явление,phenomenon
явка,appearance
явный,evident
ягода,berry
ягуар,jaguar
яд,poison
ядерный,nuclear
ядовитый,poisonous
ядро,kernel-core
язык,tongue-language
язычник,pagan
яйцо,egg
як,yak
якорь,anchor
якут,Yakut
яма,pit
ямка,dimple
ямщик,coachman
январь,January
японец,Japanese
яр,ravine
ярд,yard
яркий,bright
ярмарка,fair
ярость,fury
ярус,tier
ясень,ash-tree
ясный,clear
ясли,nursery
ясность,clarity
ястреб,hawk
яхта,yacht
ячмень,barley
ячейка,cell
ящер,pangolin
ящерица,lizard
ящик,box
яблочный,apple
явственный,distinct
ягодный,berry
ядерщик,nuclear-specialist
язва,ulcer
язвительный,caustic
яичница,fried-eggs
якорный,anchor
яловой,barren
ямщицкий,coachman
ястребок,young-hawk`;

  return raw
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l && l.indexOf(",") !== -1)
    .map((l) => {
      const i = l.indexOf(",");
      return { ru: l.slice(0, i).trim(), en: l.slice(i + 1).trim() };
    });
})();
